version: '3'
services:
        app:
                build:
                        context: .
                        dockerfile: .docker/Dockerfile
                image: abackup-web
                network_mode: bridge
                restart: always
                ports:
                        - 8092:80
